server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        ## USER SERVICE
        - id: user-account
          uri: lb://user-account
          predicates:
            - Path=/user-account/**
          filters:
            - StripPrefix=1
        ## NEWS SERVICE
        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/news-service/**
          filters:
            - StripPrefix=1

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG